app:
  port: ':7200'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

producer:
  brokers: ['192.168.0.105:9092']
  topic: 'delete.municipality.profilepicture'
  batch_size: 1
  batch_timeout: 10

health:
  address: '192.168.0.101'
  port: ':8150'
  shutdown_endpoint: '/api/v1/superhero_delete_media_health/shutdown'
  content_type: 'application/json'
